version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - target: 3000
        published: 3000
        protocol: TCP
        mode: host
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - target: 5432
        published: 5432
    restart: always
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql

volumes:
  db-data:
